### PR TITLE
Move all hide checkboxes to top

### PR DESCRIPTION
**Pull request by sphh**
This PR is born out of a personal frustration: I often check the effect of a setting by hiding/unhiding the widget. For this to work effectively, the hide checkbox should always be at the same place and easily reachable. IMHO this best place is at the very top of the settings, but #92 has a different idea (at the bottom – but then you always have to scroll down to the bottom …)

This PR implements this with the check box(es) always at the top. If the check box should be at the bottom, the method `setting.settings.Settings.getNames()` should be changed from
```python
    def getNames(self):
        """Return list of names."""
        return self.hideboxnames + self.setnames
```
to
```python
    def getNames(self):
        """Return list of names."""
        return self.setnames + self.hideboxnames
```
This could be even made a configuration option? But then I am not sure, if the reversal of
```python
   def saveText(self, saveall, rootname = None):
```
would still work, if the file is loaded with the checkboxes set to a different position …

### CODE REVIEW

**Comment by jeremysanders** [comment]
Thanks. I'll take a look. There are the new keyboard shortcuts for show/hide which should help you do this quickly.

**Comment by sphh** [comment]
Thanks.
Yes, I noticed the short cuts. They might even have motivated me to finally make this PR …

**Comment by jeremysanders** [comment]
Thanks again for the pull request. After looking at this, I think it might be the wrong way to go about doing this. Arguably, introducing another list in the Settings class seems a bit invasive. Ideally, I may have done this some time ago to make the formatting settings separate from the properties.

I think the right way is just to handle the hide setting separately in the user interface, as it is pretty fundamental. This is a pretty small change. I've put it into this branch: https://github.com/veusz/veusz/tree/hide-at-top  Be warned this is Python 3 only, but I'm planning to shortly merge a branch which will drop Python 2 compatibility.

Are you happy to do this instead? Sorry for the work you've already put into this change.

I think it might be interesting to see whether the Hide setting could be moved (or added) next to the "Main" title at the top. This would save some space and would make the checkbox be in exactly the same spot for each widget.

**Comment by sphh** [comment]
I didn't want to interfere with the code too much, so I simply tried to splice the positioning of the hide checkbox into the existing code. I am with you, believing it is a very fundamental setting. Getting it next to the "Main" title would be really the optimum!

By all means, please do not worry to much about "discarding" my PR. I think your solution is a far better one.

Do you happen to have a screenshot showing the new position of the hide checkbox. I am just curious and don't want to compile the whole lot :-o Thanks!

**Comment by jeremysanders** [comment]
I've not implemented the hide next to the title yet. This is the current state for each widget:
image

**Comment by sphh** [comment]
Thanks for the screenshot.

Would it be possible to add a visual clue to the tab, if the contents is hidden? Maybe the symbol in the tab can be greyed out?

I understood, that the hide checkbox is not yet next to the title. I just tried to voice my opinion, that this is probably a very good place to put it! If you can implement it, do you plan to put it to the left or right of the title? May I suggest to put it to the left and reverse the meaning? I believe than it looks like a simple checkbox: If it is checked, that item is visible and if it is unchecked, it is hidden. Just an idea …

**Comment by jeremysanders** [comment]
Well, here's the result of an initial implementation. I'm using an eye icon rather than a checkbox. It's greyed out if hidden. Is this better than a checkbox?
image
image

I've moved the "Hide" setting down to the bottom so it is available like the other settings (for propagation, or setting defaults). This is with the eye icon to the left (I also tried right-justifying the text, which didn't seem to work). I think I prefer the eye to the right, but opinions welcome.

image

I haven't tried greying out the tab icons. I'll have to see how much work that would be.

**Comment by sphh** [comment]
I like the checkbox/eye better on the left side. Why? It is easier so see, because the information is close together. If the eye is located on the right edge, I have to look for the title on the left side and then my eye has to move to right side to see, if it enabled or not. This is just my opinion.

But I give you that, that with the large margin around the eye button, it looks a bit weird. Is it possible to reduce the margin between the eye and the button on all four sides? This would reduce the height of the section label and I believe it will look better. Something like this:
veusz mockup

What do you think?

**Comment by jeremysanders** [comment]
Sure. I was trying to shrink the space, but I've finally worked out how to do it. I've also implemented greying of the icon at the top of each tab if hide is True:
image
Therefore I think these changes can now be put into the main repository.

**Comment by sphh** [comment]
I think that's very good and does really improve the usability!! Thanks.

One last tiny suggestion: Is it possible to reduce the horizontal spacing between the eye and the title further? The space seen in the screenshot looks a bit too large to my eye. But this is purely a tiny cosmetic improvement.

Do you think, the `Hide` setting at the bottom will not confuse the user? But this is also just cosmetic … Maybe a note in the tooltip mentioning the eye button would sort this?

**Comment by jeremysanders** [comment]
It looks a bit better with 0 space between the widgets. It doesn't seem possible to shrink the button any smaller:
image

Do you mean the Hide setting is confusing as it's at the bottom, or confusing because it exists at all? I think the visibility button is just a shortcut to setting hide, so it's ok to have both. Hopefully it's not too confusing. The hide setting also allows propagation between widgets, and resetting to default, which would be difficult to add to the visibility button.

**Comment by sphh** [comment]
I believe that looks perfect!

I can now see, why you want/need the `Hide` button: It's the additional features hidden in the drop-down menu?

I could imagine, that it is confusing because it is there at all. Without my current knowledge, that the eye is actually an active button, I would think, it's just an additional visual indicator of the state of the `Hide` button. I would think, I have to scroll down to the `Hide` button to change it until I find by accident, that I can also click onto the eye button. A tooltip along the line "Hide element (you can also click onto the eye button at the top…)" would have helped me as a novice user. But that's just my personal view …

**Comment by jeremysanders** [comment]
Yes, I wanted to retain the other features in the drop down menu. I've modified the tooltip to make it clearer what's going on.

**Comment by sphh** [comment]
Excellent! I'm looking forward to the release of the new version!!

**Comment by jeremysanders** [comment]
Thanks for your helpful suggestions and comment (and initial code). I've merged the new visibility button code into the master branch. I'll close this now.

**Comment by sphh** [comment]
It's me, who has to thank you for listening and implementing my pernickety opinions. Thanks.

**Pull request closed without merging**
