### PR TITLE
Improved fitting

### PR DESCRIPTION
**Pull request by sekoenig**
Two small improvements to fitting function: choose default Y error, set plot range and fit range independently.

### CODE REVIEW

**Comment by jeremysanders** [comment]
Thanks for the pull request. Sorry for not addressing it earlier.

I'm still not sure what the correct thing to do here is. Probably the default should be changed to a fixed absolute error, as most people are not fitting logarithmic data (where fractional errors are appropriate). Maybe there's an argument for allowing both?

Does the choice of default fractional uncertainty make much difference to your fits?

**Comment by sekoenig** [comment]
I tend to agree allowing both would be best, i.e., keep the field to add a default value for all points, but add another option indicating if this default should be relative or absolute.  How about that?

To be honest, it was so long ago that I implemented the initial patch (purely as a hack for myself then), I forget how problematic the fixed 5% default was, but I assume I had a good reason for changing it :)

**Comment by sekoenig** [comment]
Getting back to this after a long time.  I was wondering, would you consider merging just the [Set fit range independent of plot range](https://github.com/veusz/veusz/pull/439/commits/5e6352c2a9973d9bdf5a02d7462224f7837002bd) alone?

**Comment by jeremysanders** [comment]
Sorry, I've not properly looked at this. I'm a bit uneasy at changing the behaviour if people are relying on it as it currently stands. The intention was a complete rewrite so everything would change at once.

There is a mechanism for adding a new compatibility level, but the code could get a bit nasty for handling both. Maybe as it's an interactive thing, changing the behaviour isn't so bad. I'll think further.

**Comment by sekoenig** [comment]
Perhaps there is a way to implement it while keeping backwards compatibilty: introduce the `fit_min` and `fit_max` as in my commit, but have them use the `min` and `max` values when they are set to `Auto`.  I mean, `fit_min=Auto` implies `fit_min=min`, and likewise for the max values.

**Comment by jeremysanders** [comment]
Ok, as it's an interactive feature, I've decided to merge it.

However, I made some changes:
 * yDefErr -> defErr, as it could be x errors
 * I added defErrType which is 'absolute' (default) or 'relative', to make the default fitting behaviour more reasonable for non-log data

**Comment by sekoenig** [comment]
Awesome, thank you!

**Pull request merged**
